### ISSUE TITLE
Distribution

### ISSUE THREAD

**Issue by yangchoo** [JonathanxD/openaws-vpn-client#2] opened 2022-11-17 03:39 UTC
Hey! Thanks for the awesome job on this.

I happened to come across the GitHub page and only noticed the latest merged PR as a result. 

I'm comfortable pulling and building using the instructions here but I was wondering if there was any interest on your part in publishing to and maintaining an AUR package?

**Comment by JonathanxD** [comment] 2022-11-28 05:30
Sorry for the late reply, I'm currently “mirroring” the project on GitLab and releasing binaries [there](https://gitlab.com/Kores/openaws-vpn-client/-/packages) instead (since I have an annual CI/CD plan, I've been building the projects there).

The last thing I did in terms of distribution was setting up a Nix Derivation for reproducible builds. Since no one was using the project besides me (and now I know that's not true tho), I didn't bothered going further. But, given the current state, I'll be looking into it in the next few days. 

I will set a `-bin` `PKGBUILD` and push to AUR first, which may be enough for most user (given I already have the most important part of this mechanism), then I'll look into building the project with stable Rust and push a `-git` `PKGBUILD` to AUR.

Also, I will Pin this issue and let you know when it's available on AUR.

**Comment by yangchoo** [comment] 2022-11-29 15:47
@JonathanxD Awesome. Thanks for taking on the work.

Feel free to close the issue once its published to AUR and you've pasted the link here with the package name.

**Comment by JonathanxD** [comment] 2022-12-16 22:39
I finally found some time to setup it, here it is: https://aur.archlinux.org/packages/openaws-vpn-client-bin

There are some notes though:
- I'm not sure if I forgot some dependencies on the `PKGBUILD`, only time will tell. 
- `openvpn` is not a dependency, since I'm vendoring the patched version, but the `PKGBUILD` will handle everything.
- I cannot test if it's fully working as intended (I don't have access to an AWS VPN rn), but it should be. If you want to try and report back, I would appreciate.

I'll be closing as soon as I can fully ensure it's working (or someone report it's).

**Comment by mitjacotic** [comment] 2022-12-27 14:22
FYI - current aur build works for me w/o problems:)

**Comment by JonathanxD** [comment] 2023-01-23 15:54
Closing as it seems to be working fine!

**Closed by JonathanxD** 2023-01-23 15:54 UTC
